### ISSUE TITLE
When I open some forms in the source code, this error pops up

### ISSUE THREAD

**Issue by pengfan806** [groehner/guipy#10]
This is the source code of guipy. There are several windows that will report errors when opened.
<img width="796" height="660" alt="Image" src="https://github.com/user-attachments/assets/696e2017-b7bd-41b1-9be9-3d3e3268bfa2" />

<img width="1024" height="509" alt="Image" src="https://github.com/user-attachments/assets/44a0ef19-462e-47bf-a54b-8042cb2bfb4d" />

Below is the source code of pyscripter, but there is no problem opening these windows.

<img width="675" height="456" alt="Image" src="https://github.com/user-attachments/assets/a465fa8f-799c-423d-877f-970b55ee37e6" />

<img width="1004" height="746" alt="Image" src="https://github.com/user-attachments/assets/68c59448-9d54-46d4-bb8f-e917eb7cbe27" />

However, I don't have this problem when using your guipy release, so I guess it's caused by the component version.
What do you think is the cause of this problem? Is it related to the SVGIconImageList components version? Can you tell me the version of the components you are using?

Looking forward to your reply. :)

**Comment by pengfan806** [comment]
I think it is caused by the name of the icSVGImages image in dmResource.pas, which is different from the one in pyscripter.
Any good suggestions or fixes?

**Comment by groehner** [comment]
I fixed the issue.

**Comment by pengfan806** [comment]
It works, but when I configure the language to, for example, Japanese, and click the Tools and View menu items, the error still pops up, while English and German do not.

<img width="816" height="296" alt="Image" src="https://github.com/user-attachments/assets/c97262dd-fb72-4f36-b48f-d267dbd8cb61" />

<img width="585" height="285" alt="Image" src="https://github.com/user-attachments/assets/5cce2b2e-f34a-4cf2-b1e9-833f1f45f698" />

**Comment by pengfan806** [comment]
I used the 7.02 you released and it worked fine, but I compiled the exe of the master branch code myself and it had this problem.

**Comment by pengfan806** [comment]
I'm certain there's nothing wrong with my environment or components, as the compiled PyScripter doesn't have this issue. Strangely, when I set the ImageIndex property of all submenus for these two menu items to -1, the problem disappears when I compile the exe again. For example, if I set the ImageIndex property of all submenus in the Tools menu to -1, and the language is set to Japanese, clicking the Tools menu item doesn't cause this error.

<img width="468" height="276" alt="Image" src="https://github.com/user-attachments/assets/f4d0d851-c2a7-4da6-8d72-4f61acfe0f4c" />

<img width="933" height="543" alt="Image" src="https://github.com/user-attachments/assets/fe7cf35f-3cc8-4de5-99ce-59c4c3bc510c" />

**Comment by groehner** [comment]
If switching languages causes problems, gnugettext (JvGnugettext.pas) must be involved.

In ggexclude.cfg, TVirtualImageList and TAction.ImageName are excluded from translations, which would change the image names.
Everything should work just like in PyScripter.
However, I always had problems with images when switching languages in GuiPy. So I changed some names, such as "Copy" to "Copy13," to avoid them.
I haven't yet figured out why GuiPy has this problem but PyScripter doesn't.

Setting ImageIndex to -1 shouldn't have any effect, since TSpTBXItem.ImageName and
TSpTBXSubmenuItem.ImageName are excluded from gnugettext, as is TAction.ImageName, which is used to display images.

**Comment by pengfan806** [comment]
This issue should not be closed so quickly, we may be able to find the reason later.
